apiVersion: v1
kind: Namespace
metadata:
  name: listmonk
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,Prune=false
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
