apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - database.yaml
  - backup.yaml
  - runtime.yaml
  - storage.yaml
  - redis.yaml
  - workloads.yaml
  - service-route.yaml
