# k8s/applications/ai/openwebui/openwebui-external-secret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwebui-secret
  namespace: open-webui
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-cluster
    kind: ClusterSecretStore
  target:
    name: openwebui-secret
    creationPolicy: Owner
  data:
    - secretKey: WEBUI_SECRET_KEY
      remoteRef:
        key: APP_OPENWEBUI_SECRET_KEY
    - secretKey: OAUTH_CLIENT_ID
      remoteRef:
        key: "APP_OPENWEBUI_OAUTH_CLIENT_ID"
    - secretKey: OAUTH_CLIENT_SECRET
      remoteRef:
        key: "APP_OPENWEBUI_OAUTH_CLIENT_SECRET"
