---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipelines-pvc
  namespace: open-webui
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "longhorn-fast"
  resources:
    requests:
      storage: 5Gi
