apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-openwebui-pipelines-api-key
  namespace: open-webui
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-cluster
    kind: ClusterSecretStore
  target:
    name: app-openwebui-pipelines-api-key
    creationPolicy: Owner
  data:
    - secretKey: PIPELINES_API_KEY
      remoteRef:
        key: APP_OPENWEBUI_PIPELINES_API_KEY
