apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-opencode-secrets
  namespace: opencode
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-cluster
    kind: ClusterSecretStore
  target:
    name: app-opencode-secrets
    creationPolicy: Owner
  data:
    - secretKey: AUTH_SECRET
      remoteRef:
        key: APP_OPENCODE_AUTH_SECRET
    - secretKey: ADMIN_EMAIL
      remoteRef:
        key: APP_OPENCODE_ADMIN_EMAIL
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: APP_OPENCODE_ADMIN_PASSWORD
