apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie-runtime
  namespace: mealie
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-cluster
    kind: ClusterSecretStore
  target:
    name: mealie-runtime
    creationPolicy: Owner
  data:
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: APP_MEALIE_OIDC_CLIENT_SECRET
