apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mosquitto-password
  namespace: mqtt
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-cluster
    kind: ClusterSecretStore
  target:
    name: mosquitto-password
    creationPolicy: Owner
  data:
    - secretKey: MQTT_USER
      remoteRef:
        key: "APP_MQTT_USER"
    - secretKey: MQTT_PASSWORD
      remoteRef:
        key: "APP_MQTT_PASSWORD"
