apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tunnel-token
  namespace: cloudflared
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-cluster
    kind: ClusterSecretStore
  target:
    name: tunnel-token
    creationPolicy: Owner
  data:
    - secretKey: TUNNEL_TOKEN
      remoteRef:
        key: CLOUDFLARE_TUNNEL_TOKEN
