apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openclaw-talos-personal
resources:
  - namespace.yaml
  - externalsecret.yaml
  - configmap.yaml
  - serviceaccount.yaml
  - instance.yaml
  - networkpolicy.yaml
