apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: es-pinepods-admin
  namespace: pinepods
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-cluster
    kind: ClusterSecretStore
  target:
    name: es-pinepods-admin
    creationPolicy: Owner
  data:
    - secretKey: USERNAME
      remoteRef:
        key: APP_PINEPODS_ADMIN_USERNAME
    - secretKey: PASSWORD
      remoteRef:
        key: APP_PINEPODS_ADMIN_PASSWORD
    - secretKey: FULLNAME
      remoteRef:
        key: APP_PINEPODS_ADMIN_FULLNAME
    - secretKey: EMAIL
      remoteRef:
        key: APP_PINEPODS_ADMIN_EMAIL
