apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellyseerr-secrets
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-cluster
    kind: ClusterSecretStore
  target:
    name: jellyseerr-secrets
    creationPolicy: Owner
  data:
    - secretKey: JELLYFIN_URL
      remoteRef:
        key: "APP_JELLYSEERR_JELLYFIN_URL"
    - secretKey: JELLYFIN_API_KEY
      remoteRef:
        key: "APP_JELLYSEERR_JELLYFIN_API_KEY"
