apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- project.yaml
- jellyfin
- arr
- media-share-pvc.yaml
- media-layout-job.yaml
- jellyseerr
- jellyseerr-secrets.yaml
- sabnzbd
- whisperasr
- immich
- audiobookshelf
- audiobookrequest
