apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-share
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-csi
  resources:
    requests:
      storage: 2Ti
