apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-perplexica-litellm-api-key
  namespace: perplexica
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-cluster
    kind: ClusterSecretStore
  target:
    name: app-perplexica-litellm-api-key
    creationPolicy: Owner
  data:
    - secretKey: LITELLM_API_KEY
      remoteRef:
        key: APP_LITELLM_MASTER_KEY
