apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: perplexica-data
  namespace: perplexica
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-fast
  resources:
    requests:
      storage: 10Gi
