apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: chatwoot

resources:
  - namespace.yaml
  - database.yaml
  - backup.yaml
  - runtime.yaml
  - service-route.yaml
  - networkpolicy.yaml

helmCharts:
  - name: chatwoot
    repo: https://chatwoot.github.io/charts
    version: 2.0.25
    releaseName: chatwoot
    namespace: chatwoot
    valuesFile: values.yaml
