---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-longhorn-backup-secret
  namespace: litellm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-cluster
    kind: ClusterSecretStore
  target:
    name: longhorn-minio-credentials
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: INFRA_MINIO_S3_ACCESS_KEY
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: INFRA_MINIO_S3_SECRET_KEY
    - secretKey: AWS_ENDPOINTS
      remoteRef:
        key: INFRA_MINIO_S3_ENDPOINT_URL
    - secretKey: LOGICAL_BACKUP_S3_ENDPOINT
      remoteRef:
        key: INFRA_MINIO_S3_ENDPOINT_URL
