apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-secrets
  namespace: litellm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-cluster
    kind: ClusterSecretStore
  target:
    name: litellm-secrets
    creationPolicy: Owner
  data:
    - secretKey: LITELLM_MASTER_KEY
      remoteRef:
        key: APP_LITELLM_MASTER_KEY
    - secretKey: LITELLM_SALT_KEY
      remoteRef:
        key: APP_LITELLM_SALT_KEY
    - secretKey: QDRANT_API_KEY
      remoteRef:
        key: APP_QDRANT_API_KEY
    - secretKey: GENERIC_CLIENT_ID
      remoteRef:
        key: APP_LITELLM_OAUTH_CLIENT_ID
    - secretKey: GENERIC_CLIENT_SECRET
      remoteRef:
        key: APP_LITELLM_OAUTH_CLIENT_SECRET
