apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: von-secrets
  namespace: litellm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-cluster
    kind: ClusterSecretStore
  target:
    name: von-secrets
    creationPolicy: Owner
  data:
    - secretKey: VON_API_KEY
      remoteRef:
        key: APP_VON_API_KEY
    - secretKey: TYPESAFE_API_KEY
      remoteRef:
        key: APP_VON_API_KEY
