apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: von-model-cache
  namespace: litellm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-fast
  resources:
    requests:
      storage: 8Gi
