apiVersion: v1
kind: Service
metadata:
  name: von
  namespace: litellm
spec:
  type: ClusterIP
  selector:
    app: von
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
