apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: decypharr-state
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-fast
  resources:
    requests:
      storage: 2Gi
