apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - recommendations.yaml

helmCharts:
  - name: vertical-pod-autoscaler
    repo: https://kubernetes.github.io/autoscaler
    version: 0.12.0
    releaseName: vpa
    namespace: vertical-pod-autoscaler
    valuesFile: values.yaml
    includeCRDs: true
