apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kiwix-data
  namespace: kiwix
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
  labels:
    backup.smadja.dev/strategy: rebuildable
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: longhorn-bulk
