apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kubechecks-combined-secret
  namespace: kubechecks
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-cluster
    kind: ClusterSecretStore
  target:
    name: kubechecks-combined-secret
    creationPolicy: Owner
  data:
    - secretKey: github_token
      remoteRef:
        key: APP_KUBECHECKS_GITHUB_APP_KEY
    - secretKey: argocd_api_token
      remoteRef:
        key: APP_KUBECHECKS_ARGOCD_API_TOKEN
    - secretKey: webhook_hmac
      remoteRef:
        key: APP_KUBECHECKS_WEBHOOK_HMAC_SECRET
    # - secretKey: openai_key
    #   remoteRef:
    #     key: global-openai-api-key
