apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate
  namespace: renovate
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-cluster
    kind: ClusterSecretStore
  target:
    name: renovate
    creationPolicy: Owner
  data:
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: APP_RENOVATE_GITHUB_TOKEN
