apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    name: argocd-secret
    creationPolicy: Merge
  data:
    - secretKey: dex.authentik.clientSecret
      remoteRef:
        key: APP_ARGOCD_OAUTH_CLIENT_SECRET
    - secretKey: dex.authentik.clientId
      remoteRef:
        key: APP_ARGOCD_OAUTH_CLIENT_ID
