configs:
  cm:
    create: true
    application.resourceTrackingMethod: annotation
    admin.enabled: false
    url: https://argocd.smadja.dev
    kustomize.buildOptions: '--enable-helm'
    dex.config: |
      connectors:
      - config:
          issuer: https://auth.smadja.dev/application/o/argocd/
          clientID: argocd
          clientSecret: $dex.authentik.clientSecret
          insecureEnableGroups: true
          scopes:
            - openid
            - profile
            - email
            - groups
        name: authentik
        type: oidc
        id: authentik

  params:
    controller.diff.server.side: true
    server.insecure: true

  rbac:
    create: true
    policy.default: role:readonly
    policy.csv: |
      g, admin, role:admin
      g, authentik-admins, role:admin
      g, dev, role:readonly

crds:
  install: true
  keep: true

controller:
  replicas: 1
  resources:
    requests:
      cpu: 25m
      memory: 256Mi
    limits:
      memory: 1Gi
  containerSecurityContext:
    runAsNonRoot: true
    runAsUser: 999
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop: [ALL]

dex:
  enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 128Mi

redis-ha:
  enabled: false

redis:
  enabled: true
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      memory: 128Mi

server:
  autoscaling:
    enabled: false
  service:
    type: ClusterIP
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 512Mi

repoServer:
  autoscaling:
    enabled: false
  pdb:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 2Gi

applicationSet:
  replicas: 1
  pdb:
    enabled: false
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      memory: 256Mi

notifications:
  enabled: false
