apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: factory-platform-ghcr
  namespace: factory-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-cluster
    kind: ClusterSecretStore
  target:
    name: factory-platform-ghcr
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {"auths":{"ghcr.io":{"username":"SmadjaPaul","password":"{{ .token }}","auth":"{{ printf "%s:%s" "SmadjaPaul" .token | b64enc }}"}}}
  data:
    - secretKey: token
      remoteRef:
        key: APP_FACTORY_PLATFORM_GHCR_TOKEN
