#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
draft="$repo_root/k8s/applications/ai/paperclip/poc/kubernetes-execution/activation-draft"

test -f "$draft/README.md"
test -f "$draft/activation-gates.yaml"

# The activation package must remain outside the production resource graph.
! rg -n 'activation-draft' "$repo_root/k8s/applications/ai/paperclip/kustomization.yaml"

rg -q 'selectedOption: A' "$draft/activation-gates.yaml"
! rg -q '^  plugins:' "$repo_root/k8s/applications/ai/paperclip/poc/kubernetes-execution/instance-candidate.yaml"
rg -q 'bundled local-plugin path' "$repo_root/k8s/applications/ai/paperclip/poc/kubernetes-execution/instance-candidate.yaml"
rg -q 'pluginSource: bundled-local-image' "$draft/activation-gates.yaml"
rg -q 'pluginAutoInstallKey: kubernetes' "$draft/activation-gates.yaml"
rg -q 'operatorSpecPluginsConsumed: false' "$draft/activation-gates.yaml"
rg -q '30d762c59185f5b67aec3a2f8bd1ce27b44a5a2e' "$draft/activation-gates.yaml"
rg -q 'agents.x-k8s.io/v1beta1' "$draft/activation-gates.yaml"
rg -q 'v1.0.5' "$draft/activation-gates.yaml"
rg -q 'prerequisiteHead: fdd83bcf3e23cc5633bbb7a1260bd05d601de76d' "$draft/activation-gates.yaml"
rg -q 'requiredImageDigest: pending-published-image-with-kubernetes-plugin' "$draft/activation-gates.yaml"
rg -q 'prerequisiteMergeCommit: be721124bfd9dc8566d77b0e04a3c38dcc0db283' "$draft/activation-gates.yaml"
rg -q 'prerequisitePullRequest: 15' "$draft/activation-gates.yaml"
rg -q 'networkFixPullRequest: 16' "$draft/activation-gates.yaml"
rg -q 'networkFixHead: 73c654e6eaabb07ef7594c6e53ccc70cb8318376' "$draft/activation-gates.yaml"
rg -q 'paperclip15Merged: true' "$draft/activation-gates.yaml"
rg -q 'kindCiRun: 38089528661' "$draft/activation-gates.yaml"
rg -q 'imageCiRun: 38090000606' "$draft/activation-gates.yaml"
rg -q 'paperclip11Merged: true' "$draft/activation-gates.yaml"
rg -q 'paperclip14Merged: true' "$draft/activation-gates.yaml"
rg -q 'ciKindSandboxRuntimeProof: true' "$draft/activation-gates.yaml"
rg -q 'ciBundledImageVerified: true' "$draft/activation-gates.yaml"
rg -q 'pods/exec/get, pods/exec/create' "$draft/activation-gates.yaml"
rg -q 'replacementImagePublishedAndPinned: false' "$draft/activation-gates.yaml"
rg -q 'paperclipSandboxCallbackEgressSelectorObserved: false' "$draft/activation-gates.yaml"
rg -q 'existingTenantNetworkPolicyDriftAudited: false' "$draft/activation-gates.yaml"
rg -q 'paperclipServerPluginLoadObserved: false' "$draft/activation-gates.yaml"
rg -q 'litellmScopedVirtualKeyInjectedIntoSandbox: false' "$draft/activation-gates.yaml"
rg -q 'disposableRuntimeProof: false' "$draft/activation-gates.yaml"
rg -q 'status: blocked-human-gate' "$draft/activation-gates.yaml"
rg -q 'h3HumanApproval: false' "$draft/activation-gates.yaml"
rg -q 'orchestratorApproval: false' "$draft/activation-gates.yaml"
rg -q 'namespaceScope: persistent-per-company' "$draft/activation-gates.yaml"
rg -q 'namespaceDeleteDuringRunCleanup: false' "$draft/activation-gates.yaml"
rg -q 'scope: every-existing-tenant-namespace' "$draft/activation-gates.yaml"
rg -q 'resourcequota' "$draft/activation-gates.yaml"
rg -q 'ciliumnetworkpolicy' "$draft/activation-gates.yaml"
rg -q 'mismatchResult: blocker' "$draft/activation-gates.yaml"
rg -q 'autoRepair: false' "$draft/activation-gates.yaml"
rg -q 'while the tenant namespace remains' "$draft/README.md"
! rg -q 'tenant namespace are cleaned up' "$draft/README.md"

echo 'paperclip sandbox activation draft: PASS (non-live and fail-closed)'
