apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: media

resources:
- oidc-external-secret.yaml
- bootstrap-external-secret.yaml
- bootstrap-job.yaml
- http-route.yaml
- statefulset.yaml
- svc.yaml
- service-account.yaml
