apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seerr-oidc
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-cluster
    kind: ClusterSecretStore
  target:
    name: seerr-oidc
    creationPolicy: Owner
  data:
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: APP_JELLYSEERR_OAUTH_CLIENT_ID
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: APP_JELLYSEERR_OAUTH_CLIENT_SECRET
