apiVersion: http.keda.sh/v1beta1
kind: InterceptorRoute
metadata:
  name: pocket-tts
  namespace: pocket-tts
spec:
  target:
    service: pocket-tts
    port: 49112
  rules:
    - hosts:
        - tts.smadja.dev
  scalingMetric:
    concurrency:
      targetValue: 1
  coldStart:
    maxPendingRequests: 4
    overflow: Reject
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: pocket-tts
  namespace: pocket-tts
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pocket-tts
  minReplicaCount: 0
  maxReplicaCount: 1
  cooldownPeriod: 600
  pollingInterval: 15
  triggers:
    - type: external-push
      metadata:
        scalerAddress: keda-add-ons-http-external-scaler.keda:9090
        interceptorRoute: pocket-tts
