apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vikunja-runtime
  namespace: vikunja
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-cluster
    kind: ClusterSecretStore
  target:
    name: vikunja-runtime
    creationPolicy: Owner
  data:
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef: { key: APP_VIKUNJA_OIDC_CLIENT_SECRET }
