apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata: { name: vikunja-app, namespace: vikunja }
spec:
  endpointSelector: { matchLabels: { app.kubernetes.io/name: vikunja } }
  ingress:
    - fromEntities: [host, remote-node, ingress]
      toPorts:
        - ports:
            - { protocol: TCP, port: "3456" }
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata: { name: vikunja-postgresql, namespace: vikunja }
spec:
  endpointSelector: { matchLabels: { cnpg.io/cluster: vikunja-postgresql } }
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: vikunja
            app.kubernetes.io/name: vikunja
      toPorts:
        - ports:
            - { protocol: TCP, port: "5432" }
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: cnpg-system
      toPorts:
        - ports:
            - { protocol: TCP, port: "8000" }
