apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-gpt-researcher-litellm-api-key
  namespace: gpt-researcher
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-cluster
    kind: ClusterSecretStore
  target:
    name: app-gpt-researcher-litellm-api-key
    creationPolicy: Owner
  data:
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: APP_GPTRESEARCHER_LITELLM_API_KEY
