apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gpt-researcher-secrets
  namespace: gpt-researcher
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-cluster
    kind: ClusterSecretStore
  target:
    name: gpt-researcher-secrets
    creationPolicy: Owner
  data:
    - secretKey: TAVILY_API_KEY
      remoteRef:
        key: APP_GPT_RESEARCHER_TAVILY_API_KEY
    - secretKey: LANGCHAIN_API_KEY
      remoteRef:
        key: APP_GPT_RESEARCHER_LANGCHAIN_API_KEY
