apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frigate-rstp-credentials
  namespace: frigate
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-cluster
    kind: ClusterSecretStore
  target:
    name: frigate-rstp-credentials
    creationPolicy: Owner
  data:
    - secretKey: FRIGATE_RTSP_USERNAME
      remoteRef:
        key: APP_FRIGATE_RTSP_USERNAME
    - secretKey: FRIGATE_RTSP_PASSWORD
      remoteRef:
        key: APP_FRIGATE_RTSP_PASSWORD
    - secretKey: FRIGATE_RTSP_SUB
      remoteRef:
        key: APP_FRIGATE_RTSP_SUB_STREAM_URL
    - secretKey: FRIGATE_RTSP_MAIN
      remoteRef:
        key: APP_FRIGATE_RTSP_MAIN_STREAM_URL
    - secretKey: FRIGATE_ONVIF
      remoteRef:
        key: APP_FRIGATE_ONVIF_PASSWORD
    - secretKey: FRIGATE_MQTT_USER
      remoteRef:
        key: APP_MQTT_USER
    - secretKey: FRIGATE_MQTT_PASSWORD
      remoteRef:
        key: APP_MQTT_PASSWORD
