apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: velero

resources:
  - namespace.yaml
  - externalsecret.yaml
  - schedules/
  - backup-smoke-20260929.yaml
  - prometheusrule.yaml

helmCharts:
  - name: velero
    repo: https://vmware-tanzu.github.io/helm-charts
    version: 12.0.1
    releaseName: velero
    namespace: velero
    valuesFile: values.yaml
