apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- project.yaml
# Disabled for initial bootstrap: hardware/camera-dependent workload
# - frigate
- mqtt
- hassio
- zigbee2mqtt
- matter-server
