apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: listmonk-postgresql
  namespace: listmonk
spec:
  instances: 1
  bootstrap:
    initdb:
      database: listmonk
      owner: listmonk
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: listmonk-hetzner-store
  storage:
    size: 10Gi
    storageClass: proxmox-csi
  affinity:
    enablePodAntiAffinity: false
