apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: listmonk-runtime
  namespace: listmonk
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-cluster
    kind: ClusterSecretStore
  target:
    name: listmonk-runtime
    creationPolicy: Owner
  data:
    - secretKey: LISTMONK_ADMIN_USER
      remoteRef: { key: APP_LISTMONK_ADMIN_USER }
    - secretKey: LISTMONK_ADMIN_PASSWORD
      remoteRef: { key: APP_LISTMONK_ADMIN_PASSWORD }
