apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: invoice-ninja-runtime
  namespace: invoice-ninja
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-cluster
    kind: ClusterSecretStore
  target:
    name: invoice-ninja-runtime
    creationPolicy: Owner
  data:
    - secretKey: APP_KEY
      remoteRef: { key: APP_INVOICE_NINJA_APP_KEY }
    - secretKey: DB_PASSWORD
      remoteRef: { key: APP_INVOICE_NINJA_DB_PASSWORD }
    - secretKey: IN_PASSWORD
      remoteRef: { key: APP_INVOICE_NINJA_INITIAL_ADMIN_PASSWORD }
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef: { key: APP_INVOICE_NINJA_OIDC_CLIENT_SECRET }
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: invoice-ninja-mysql
  namespace: invoice-ninja
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-cluster
    kind: ClusterSecretStore
  target:
    name: invoice-ninja-mysql
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_PASSWORD
      remoteRef: { key: APP_INVOICE_NINJA_DB_PASSWORD }
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef: { key: APP_INVOICE_NINJA_DB_ROOT_PASSWORD }
