apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - externalsecret.yaml
  - config.yaml
  - storage.yaml
  - backup-logical.yaml
  - mysql.yaml
  - redis.yaml
  - deployment.yaml
  - service-route.yaml
  - networkpolicy.yaml
