apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openbao-seal
  namespace: openbao
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster
  target:
    creationPolicy: Owner
    name: openbao-seal
  data:
    - secretKey: OPENBAO_SEAL_KEY
      remoteRef:
        key: OPENBAO_SEAL_KEY
