apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cert-manager-secrets
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: bitwardensecret
    app.kubernetes.io/instance: cert-manager-secrets
    app.kubernetes.io/managed-by: kustomize
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-cluster  # Uses the ClusterSecretStore
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-token
    creationPolicy: Owner
  data:
  - secretKey: cloudflare-api-token
    remoteRef:
      key: INFRA_CLOUDFLARE_API_TOKEN
  - secretKey: email
    remoteRef:
      key: INFRA_CLOUDFLARE_ADMIN_EMAIL
