apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cert-manager-lechaplais-secrets
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-cluster
    kind: ClusterSecretStore
  target:
    name: cloudflare-lechaplais-api-token
    creationPolicy: Owner
  data:
    - secretKey: cloudflare-api-token
      remoteRef:
        key: APP_LECHAPLAIS_CLOUDFLARE_DNS_API_TOKEN
