apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: romm-runtime
  namespace: romm
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-cluster
    kind: ClusterSecretStore
  target:
    name: romm-runtime
    creationPolicy: Owner
  data:
    - secretKey: ROMM_AUTH_SECRET_KEY
      remoteRef:
        key: APP_ROMM_AUTH_SECRET_KEY
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: APP_ROMM_OAUTH_CLIENT_ID
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: APP_ROMM_OAUTH_CLIENT_SECRET
