apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: romm
resources:
  - namespace.yaml
  - externalsecret.yaml
  - database-s3-credentials.yaml
  - database-objectstore.yaml
  - database.yaml
  - database-scheduled-backup.yaml
  - pvcs.yaml
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - networkpolicy.yaml
