apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ntfy-runtime
  namespace: ntfy
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-cluster
    kind: ClusterSecretStore
  target:
    name: ntfy-runtime
    creationPolicy: Owner
  data:
    - secretKey: NTFY_PASSWORD
      remoteRef:
        key: APP_NTFY_ADMIN_PASSWORD
