apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stalwart-bootstrap
  namespace: stalwart
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-cluster
    kind: ClusterSecretStore
  target:
    name: stalwart-bootstrap
    creationPolicy: Owner
  data:
    - secretKey: STALWART_RECOVERY_ADMIN
      remoteRef:
        key: APP_STALWART_RECOVERY_ADMIN
