apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: deployment
  namespace: argocd
  labels:
    smadja.dev/component: deployment
spec:
  description: Project for core infrastructure deployment
  sourceRepos:
    - 'https://github.com/SmadjaPaul/kube-ops.git'
  destinations:
    - namespace: 'argocd'
      server: '*'
    - namespace: 'kube-system'
      server: '*'
    - namespace: 'kubechecks'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
