existingConfigSecret: proxmox-csi-plugin
existingConfigSecretKey: config.yaml

storageClass:
  - name: proxmox-csi
    cache: writethrough
    fstype: ext4
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
    ssd: true
    storage: tank-vm
    mountOptions:
      - noatime
    default: true
