apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: twenty-postgresql
  namespace: twenty
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,Prune=false
spec:
  instances: 1
  bootstrap:
    initdb:
      database: twenty
      owner: twenty
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: twenty-hetzner-store
  storage:
    size: 10Gi
    storageClass: longhorn-fast
  affinity:
    enablePodAntiAffinity: false
