apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: twenty-storage
  namespace: twenty
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,Prune=false
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn-fast
  resources:
    requests:
      storage: 5Gi
