apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: holmes-ingress
  namespace: agent-observers
spec:
  podSelector:
    matchLabels:
      sre.smadja.dev/component: holmes
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 80
