apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bulwark-runtime
  namespace: bulwark
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-cluster
    kind: ClusterSecretStore
  target:
    name: bulwark-runtime
    creationPolicy: Owner
  data:
    - secretKey: SESSION_SECRET
      remoteRef:
        key: APP_BULWARK_SESSION_SECRET
