apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bulwark-data
  namespace: bulwark
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: proxmox-csi
  resources:
    requests:
      storage: 2Gi
