apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: searxng-runtime
  namespace: searxng
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-cluster
    kind: ClusterSecretStore
  target:
    name: searxng-runtime
    creationPolicy: Owner
  data:
    - secretKey: SEARXNG_SECRET
      remoteRef:
        key: APP_SEARXNG_SECRET
