apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - gatekeeper
  - kyverno
  - trivy-operator
  - falco
  - policies
  - monitoring.yaml
  - externalsecret.yaml
