apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: audiobookshelf-oidc
  namespace: media
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: doppler-cluster
    kind: ClusterSecretStore
  target:
    name: audiobookshelf-oidc
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: APP_AUDIOBOOKSHELF_OAUTH_CLIENT_ID
    - secretKey: client_secret
      remoteRef:
        key: APP_AUDIOBOOKSHELF_OAUTH_CLIENT_SECRET
