apiVersion: http.keda.sh/v1beta1
kind: InterceptorRoute
metadata:
  name: it-tools
  namespace: it-tools
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  target:
    service: it-tools-service
    port: 8080
  rules:
    - hosts:
        - ittools.smadja.dev
  scalingMetric:
    concurrency:
      targetValue: 10
  coldStart:
    maxPendingRequests: 100
  timeouts:
    readiness: 60s
    responseHeader: 15s
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: it-tools
  namespace: it-tools
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: it-tools
  minReplicaCount: 0
  maxReplicaCount: 1
  cooldownPeriod: 300
  triggers:
    - type: external-push
      metadata:
        scalerAddress: keda-add-ons-http-external-scaler.keda:9090
        interceptorRoute: it-tools
