apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-ntfy-publisher
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-cluster
    kind: ClusterSecretStore
  target:
    name: alertmanager-ntfy-publisher
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: APP_ALERTMANAGER_NTFY_PUBLISHER_TOKEN
        property: value
