apiVersion: v1
kind: ConfigMap
metadata:
  name: messages-config
  namespace: messages
data:
  DJANGO_CONFIGURATION: Production
  DJANGO_SETTINGS_MODULE: messages.settings
  DJANGO_ALLOWED_HOSTS: messages.smadja.dev
  LOGGING_LEVEL_HANDLERS_CONSOLE: INFO
  LOGGING_LEVEL_LOGGERS_ROOT: INFO
  LOGGING_LEVEL_LOGGERS_APP: INFO

  REDIS_URL: redis://messages-redis:6379
  CELERY_BROKER_URL: redis://messages-redis:6379
  OPENSEARCH_INDEX_THREADS: "False"

  AWS_S3_ENDPOINT_URL: https://fsn1.your-objectstorage.com
  AWS_S3_REGION_NAME: fsn1
  AWS_STORAGE_BUCKET_NAME: smadja-dev-messages-media
  AWS_S3_SIGNATURE_VERSION: s3v4
  STORAGE_MESSAGE_IMPORTS_ENDPOINT_URL: https://fsn1.your-objectstorage.com
  STORAGE_MESSAGE_IMPORTS_REGION_NAME: fsn1
  STORAGE_MESSAGE_IMPORTS_BUCKET_NAME: smadja-dev-messages-imports
  STORAGE_MESSAGE_IMPORTS_EXPIRE_POLICY: "600"
  STORAGE_MESSAGE_BLOBS_ENDPOINT_URL: https://fsn1.your-objectstorage.com
  STORAGE_MESSAGE_BLOBS_REGION_NAME: fsn1
  STORAGE_MESSAGE_BLOBS_BUCKET_NAME: smadja-dev-messages-blobs
  MESSAGES_BLOBS_OFFLOAD_ENABLED: "False"

  OIDC_RP_CLIENT_ID: messages
  OIDC_RP_SIGN_ALGO: RS256
  OIDC_RP_SCOPES: openid email
  OIDC_CREATE_USER: "True"
  OIDC_OP_AUTHORIZATION_ENDPOINT: https://auth.smadja.dev/application/o/authorize/
  OIDC_OP_TOKEN_ENDPOINT: https://auth.smadja.dev/application/o/token/
  OIDC_OP_USER_ENDPOINT: https://auth.smadja.dev/application/o/userinfo/
  OIDC_OP_JWKS_ENDPOINT: https://auth.smadja.dev/application/o/messages/jwks/
  OIDC_OP_LOGOUT_ENDPOINT: https://auth.smadja.dev/application/o/messages/end-session/
  OIDC_REDIRECT_ALLOWED_HOSTS: messages.smadja.dev
  OIDC_REDIRECT_REQUIRE_HTTPS: "True"
  LOGIN_REDIRECT_URL: https://messages.smadja.dev
  LOGIN_REDIRECT_URL_FAILURE: https://messages.smadja.dev
  LOGOUT_REDIRECT_URL: https://messages.smadja.dev

  IDENTITY_PROVIDER: ""
  MTA_OUT_MODE: relay
  MTA_OUT_SMTP_TLS_SECURITY_LEVEL: secure
  INSTANCE_URL: https://messages.smadja.dev
  DJANGO_EMAIL_USE_TLS: "True"
  DJANGO_EMAIL_BRAND_NAME: Smadja
  FEATURE_AI_SUMMARY: "False"
  FEATURE_AI_AUTOLABELS: "False"
  PUSH_ENABLED: "False"
