apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: messages-postgresql
  namespace: messages
spec:
  instances: 1
  bootstrap:
    initdb:
      database: messages
      owner: messages
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: messages-hetzner-store
  storage:
    size: 20Gi
    storageClass: proxmox-csi
  affinity:
    enablePodAntiAffinity: false
