apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: messages-runtime
  namespace: messages
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-cluster
    kind: ClusterSecretStore
  target:
    name: messages-runtime
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DJANGO_SECRET_KEY: "{{ .DJANGO_SECRET_KEY }}"
        OIDC_RP_CLIENT_SECRET: "{{ .OIDC_RP_CLIENT_SECRET }}"
        MDA_API_SECRET: "{{ .MDA_API_SECRET }}"
        SALT_KEY: "{{ .SALT_KEY }}"
        AWS_S3_ACCESS_KEY_ID: "{{ .S3_ACCESS_KEY_ID }}"
        AWS_S3_SECRET_ACCESS_KEY: "{{ .S3_SECRET_ACCESS_KEY }}"
        STORAGE_MESSAGE_IMPORTS_ACCESS_KEY: "{{ .S3_ACCESS_KEY_ID }}"
        STORAGE_MESSAGE_IMPORTS_SECRET_KEY: "{{ .S3_SECRET_ACCESS_KEY }}"
        STORAGE_MESSAGE_BLOBS_ACCESS_KEY: "{{ .S3_ACCESS_KEY_ID }}"
        STORAGE_MESSAGE_BLOBS_SECRET_KEY: "{{ .S3_SECRET_ACCESS_KEY }}"
        MTA_OUT_RELAY_HOST: "{{ .SMTP_HOST }}:{{ .SMTP_PORT }}"
        MTA_OUT_RELAY_USERNAME: "{{ .SMTP_USER }}"
        MTA_OUT_RELAY_PASSWORD: "{{ .SMTP_PASSWORD }}"
        DJANGO_EMAIL_HOST: "{{ .SMTP_HOST }}"
        DJANGO_EMAIL_PORT: "{{ .SMTP_PORT }}"
        DJANGO_EMAIL_HOST_USER: "{{ .SMTP_USER }}"
        DJANGO_EMAIL_HOST_PASSWORD: "{{ .SMTP_PASSWORD }}"
  data:
    - secretKey: DJANGO_SECRET_KEY
      remoteRef: { key: APP_MESSAGES_DJANGO_SECRET_KEY }
    - secretKey: OIDC_RP_CLIENT_SECRET
      remoteRef: { key: APP_MESSAGES_OIDC_CLIENT_SECRET }
    - secretKey: MDA_API_SECRET
      remoteRef: { key: APP_MESSAGES_MDA_API_SECRET }
    - secretKey: SALT_KEY
      remoteRef: { key: APP_MESSAGES_SALT_KEY }
    - secretKey: S3_ACCESS_KEY_ID
      remoteRef: { key: HETZNER_S3_ACCESS_KEY_ID }
    - secretKey: S3_SECRET_ACCESS_KEY
      remoteRef: { key: HETZNER_S3_SECRET_ACCESS_KEY }
    - secretKey: SMTP_HOST
      remoteRef: { key: MIGADU_SMTP_HOST }
    - secretKey: SMTP_PORT
      remoteRef: { key: MIGADU_SMTP_PORT }
    - secretKey: SMTP_USER
      remoteRef: { key: MIGADU_SMTP_USER }
    - secretKey: SMTP_PASSWORD
      remoteRef: { key: MIGADU_SMTP_PASSWORD }
