apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: business
  namespace: argocd
spec:
  description: Business applications
  sourceRepos:
    - https://github.com/SmadjaPaul/kube-ops.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
