apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellyfin-sso
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-cluster
    kind: ClusterSecretStore
  target:
    name: jellyfin-sso
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: APP_JELLYFIN_OAUTH_CLIENT_ID
    - secretKey: client_secret
      remoteRef:
        key: APP_JELLYFIN_OAUTH_CLIENT_SECRET
