apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-unifi-webhook
  namespace: external-dns-private
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-cluster
    kind: ClusterSecretStore
  target:
    name: external-dns-unifi-webhook
    creationPolicy: Owner
  data:
    - secretKey: UNIFI_HOST
      remoteRef:
        key: UNIFI_API
    - secretKey: UNIFI_API_KEY
      remoteRef:
        key: EXTERNALDNS_UNIFI_API_KEY
    - secretKey: UNIFI_SITE
      remoteRef:
        key: UNIFI_SITE
    - secretKey: UNIFI_VERIFY_SSL
      remoteRef:
        key: UNIFI_VERIFY_SSL