apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: recyclarr-arr-api
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-cluster
    kind: ClusterSecretStore
  target:
    name: recyclarr-arr-api
    creationPolicy: Owner
  data:
    - secretKey: RADARR_API_KEY
      remoteRef:
        key: APP_RADARR_API_KEY
    - secretKey: SONARR_API_KEY
      remoteRef:
        key: APP_SONARR_API_KEY
