{{ config(materialized='table') }}

select
    task_id,
    intent_id,
    project_id,
    repository_id,
    pr_id,
    task_type,
    priority,
    environment,
    agent_id,
    provider,
    model_name,
    intent_at,
    started_at,
    pr_opened_at,
    review_requested_at,
    first_review_response_at,
    accepted_at,
    source_last_event_at,
    cast(intent_at as date) as intent_date,
    cast(accepted_at as date) as accepted_date,
    acceptance_attempt_number,
    accepted_task_flag,
    end_to_end_cycle_time_seconds,
    first_pass_success_flag,
    human_oversight_minutes_per_success,
    cost_per_accepted_task,
    change_failure_count,
    case when deployment_count > 0 then change_failure_count::numeric / deployment_count end as change_fail_rate,
    deployment_count,
    rework_deployment_count,
    case when deployment_count > 0 then rework_deployment_count::numeric / deployment_count end as deployment_rework_rate,
    ci_run_count,
    ci_retry_count,
    human_oversight_minutes,
    attributed_cost_usd,
    review_rounds,
    review_turnaround_minutes,
    input_tokens,
    output_tokens,
    tool_calls,
    pr_additions,
    pr_deletions,
    pr_files_changed,
    task_complexity_score,
    task_complexity_band,
    context_quality_score,
    context_quality_band,
    classification_confidence,
    innovation_eligible_flag,
    innovation_task_flag,
    innovation_success_flag
from {{ ref('fct_delivery_task') }}
