apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- project.yaml
- argocd
- argocd-mcp
- grafana-mcp
- cert-manager
- descheduler
- external-secrets
- reloader
- keda
- metrics-server
- velero
- node-feature-discovery
- paperclip-operator
- openclaw-operator
