apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: controllers
  namespace: argocd
  labels:
    smadja.dev/component: controllers
spec:
  description: Project for core infrastructure controllers
  sourceRepos:
    - 'https://github.com/SmadjaPaul/kube-ops.git'
    - 'ghcr.io/paperclipinc/charts'
  destinations:
    - namespace: 'argocd'
      server: '*'
    - namespace: 'kube-system'
      server: '*'
    - namespace: 'velero'
      server: '*'
    - namespace: 'paperclip-operator-system'
      server: '*'
    - namespace: 'openclaw-operator-system'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
