apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hassio-secrets
  namespace: home-assistant
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-cluster
    kind: ClusterSecretStore
  target:
    name: hassio-secrets
    creationPolicy: Owner
  data:
    - secretKey: secrets.yaml
      remoteRef:
        key: "APP_HASSIO_SECRETS"
