apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hassio-secrets
  namespace: home-assistant
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: doppler-cluster
    kind: ClusterSecretStore
  target:
    name: hassio-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        secrets.yaml: |
          ha_oidc_client_id: {{ .ha_oidc_client_id | quote }}
          ha_oidc_client_secret: {{ .ha_oidc_client_secret | quote }}
  data:
    - secretKey: ha_oidc_client_id
      remoteRef:
        key: APP_HASSIO_OAUTH_CLIENT_ID
    - secretKey: ha_oidc_client_secret
      remoteRef:
        key: APP_HASSIO_OAUTH_CLIENT_SECRET
