apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ai
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/SmadjaPaul/kube-ops.git'
  destinations:
    - namespace: 'karakeep'
      server: '*'
    - namespace: 'open-webui'
      server: '*'
    - namespace: 'bytebot'
      server: '*'
    - namespace: 'litellm'
      server: '*'
    - namespace: 'qdrant'
      server: '*'
    - namespace: 'vllm-embed'
      server: '*'
    - namespace: 'openclaw'
      server: '*'
    - namespace: 'openclaw-talos-personal'
      server: '*'
    - namespace: 'openclaw-talos-ops'
      server: '*'
    - namespace: 'openclaw-talos-test'
      server: '*'
    - namespace: 'opencode'
      server: '*'
    - namespace: 'paperclip'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
