apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: velero-daily-paperclip
  namespace: velero
  labels:
    backup-tier: daily
    backup-app: paperclip
spec:
  schedule: "15 2 * * *"
  template:
    includedNamespaces:
      - paperclip
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: paperclip
        app.kubernetes.io/component: server
    includedResources:
      - '*'
    excludedResources:
      - events
      - storageclasses.storage.k8s.io
      - clusters.postgresql.cnpg.io
      - backups.postgresql.cnpg.io
      - scheduledbackups.postgresql.cnpg.io
    defaultVolumesToFsBackup: true
    storageLocation: default
    ttl: 336h
