apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: velero-daily-monitoring
  namespace: velero
  labels:
    backup-tier: daily
    backup-app: monitoring
spec:
  schedule: "30 1 * * *"
  template:
    includedNamespaces:
      - monitoring
    includedResources:
      - '*'
    excludedResources:
      - events
      - storageclasses.storage.k8s.io
    defaultVolumesToFsBackup: true
    storageLocation: default
    ttl: 336h
