apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: velero-daily-listmonk
  namespace: velero
  labels:
    backup-tier: daily
    backup-app: listmonk
spec:
  schedule: "45 2 * * *"
  template:
    includedNamespaces:
      - listmonk
    includedResources:
      - '*'
    excludedResources:
      - events
      - storageclasses.storage.k8s.io
      - clusters.postgresql.cnpg.io
      - backups.postgresql.cnpg.io
      - scheduledbackups.postgresql.cnpg.io
      - objectstores.barmancloud.cnpg.io
    defaultVolumesToFsBackup: true
    storageLocation: default
    ttl: 336h
