apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: velero-daily-romm
  namespace: velero
  labels:
    backup-tier: daily
    backup-app: romm
spec:
  schedule: "25 2 * * *"
  template:
    includedNamespaces:
      - romm
    labelSelector:
      matchLabels:
        backup.smadja.dev/velero: "true"
    includedResources:
      - '*'
    excludedResources:
      - events
      - storageclasses.storage.k8s.io
      - clusters.postgresql.cnpg.io
      - backups.postgresql.cnpg.io
      - scheduledbackups.postgresql.cnpg.io
      - objectstores.barmancloud.cnpg.io
    defaultVolumesToFsBackup: true
    storageLocation: default
    ttl: 336h
