apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: immich-hetzner-store
  namespace: immich
spec:
  retentionPolicy: "14d"
  configuration:
    destinationPath: s3://smadja-dev-homelab-backups/cnpg/immich
    endpointURL: https://fsn1.your-objectstorage.com
    s3Credentials:
      accessKeyId:
        name: cnpg-hetzner-credentials
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: cnpg-hetzner-credentials
        key: AWS_SECRET_ACCESS_KEY
    wal:
      compression: gzip
      maxParallel: 2
    data:
      compression: gzip
